[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install"

[deploy]
startCommand = "cd backend && npm run migrate:undo && npm run migrate && node index.js"
restartPolicyType = "ON_FAILURE"

[mount]
source = "backend"
destination = "/app"

[service]
name = "TVGM"